export const ADD_CHAT_USER = 'ADD_CHAT_USER';
export const REMOVE_CHAT_USER = 'REMOVE_CHAT_USER';
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const LOAD_USER_LIST_AND_MESSAGES = 'LOAD_USER_LIST_AND_MESSAGES';
export const LOAD_USER_LIST_AND_MESSAGES_REQUEST = 'LOAD_USER_LIST_AND_MESSAGES_REQUEST';
