export const ADD_CHAT_USER = 'ADD_CHAT_USER';
export const REMOVE_CHAT_USER = 'REMOVE_CHAT_USER';
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const LOAD_USER_LIST_AND_MESSAGES = 'LOAD_USER_LIST_AND_MESSAGES';
export const LOAD_USER_LIST_AND_MESSAGES_REQUEST = 'LOAD_USER_LIST_AND_MESSAGES_REQUEST';
export const SET_CURRENT_USER_VIEW = 'SET_CURRENT_USER_VIEW';
export const NOTIFY_NEW_MESSAGE = 'NOTIFY_NEW_MESSAGE';
export const REMOVE_NOTIFY_NEW_MESSAGE = 'REMOVE_NOTIFY_NEW_MESSAGE';
