export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_AUTHDATA = 'SET_AUTHDATA';
export const CLEAR_AUTHDATA = 'CLEAR_AUTHDATA';
